name: "Setup and install"
description: "Common setup steps for Actions"

runs:
  using: composite
  steps:
    - uses: pnpm/action-setup@v3
    - uses: actions/setup-node@v6
      with:
        node-version: 20
        cache: "pnpm"
    - uses: actions/setup-go@v6
    - shell: bash
      run: pnpm install
    - shell: bash
      run: go mod tidy
