version: 2
before:
  hooks:
    - go mod tidy
builds:
  - main: ./cmd/main.go
    id: "pushpop"
    binary: pushpop
    env:
      - CGO_ENABLED=0
    goos:
      - linux
    goarch:
      - amd64
      - arm64
    ldflags: -s -w -X main.Version=v{{ .Version }} -X main.CommitSHA={{ .Commit }} -X main.CommitDate={{ .CommitDate }}
    no_unique_dist_dir: false
checksum: 
  name_template: "checksums.txt"

dockers:
  - id: "pushpop"
    goos: linux
    image_templates:
      - "ghcr.io/biohackerellie/pushpop:latest"

source:
  enabled: true

