name: CI

on:
  pull_request:
    branches: ["*"]
  merge_group:

jobs:
  lint:
    runs-on: ubuntu-latest
    name: Run Biome
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: ./.github/actions/setup

      - run: pnpm turbo lint

  check-changeset:
    runs-on: ubuntu-latest
    name: Check Changeset
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: ./.github/actions/setup

      - name: Check and Validate Changes 
        run: |
          git fetch origin main:main
          changes=$(git diff --name-only main...${{ github.sha }} | grep '^ts-client/\|.go' || true)
          if [[ -n "$changes" ]]; then
            echo "Changes detected : $changes"
            pnpm changeset status --since origin/main
            exit_status=$?
            if [[ $exit_status -eq 0 ]]; then
              echo "Changeset validation succeeded."
            else
              echo "Changeset validation failed."
            fi
          else
            echo "No changes detected "
          fi
  tsc:
    runs-on: ubuntu-latest
    name: Run Typechecker
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: ./.github/actions/setup

      - run: pnpm typecheck
