# Originally inspired by Cloudflare Wrangler
# https://github.com/cloudflare/wrangler2/blob/main/.github/workflows/release.yml

name: Release
env:
  REGISTRY: ghcr.io
  GOAPI_IMAGE_NAME: biohackerellie/pushpop
on: 
  push:
    branches:
      - main

jobs:
  release:
    if: ${{ github.repository_owner == 'biohackerellie' }}
    name: Create a PR for release workflow
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: ./.github/actions/setup

      - name: Check for errors
        run: pnpm turbo lint

      - name: Build the package
        run: pnpm turbo build

      - name: Create Version PR or Publish to NPM
        id: changesets
        uses: changesets/action@v1
        with:
          commit: "chore(release): version packages"
          title: "chore(release): version packages"
          version: node .github/changeset-version.js
          publish: npx changeset publish
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
          NODE_ENV: "production"

      - name: Log in to the Container registry
        uses: docker/login-action@327cd5a69de6c009b9ce71bce8395f28e651bf99
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract metadata (tags, labels) for Docker
        if: steps.changesets.outputs.published == 'true'
        id: meta
        uses: docker/metadata-action@8e1d5461f02b7886d3c1a774bfbd873650445aa2
        with:
          images: ${{ env.REGISTRY }}/${{ env.GOAPI_IMAGE_NAME}}
          flavor: |
            latest=true
          tags: |
            type=ref,event=branch
            type=schedule,enable=true,priority=1000,prefix=,suffix=,pattern=nightly
            type=match,pattern=v(.*),group=1
          labels: |
            org.opencontainers.image.title=${{env.GOAPI_IMAGE_NAME}}
            org.opencontainers.image.description=Simple Container for Websockets
            org.opencontainers.image.vendor=Biohackerellie
      - name: Set up Docker Buildx
        if: steps.changesets.outputs.published == 'true'
        uses: docker/setup-buildx-action@v3

      - name: Build and push Docker image
        if: steps.changesets.outputs.published == 'true'
        id: push
        uses: docker/build-push-action@v6
        with:
          context: .
          file: Dockerfile
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
      - name: Generate artifact attestation
        if: steps.changesets.outputs.published == 'true'
        uses: actions/attest-build-provenance@v2
        with:
          subject-name: ${{ env.REGISTRY }}/${{ env.GOAPI_IMAGE_NAME}}
          subject-digest: ${{ steps.push.outputs.digest }}
          push-to-registry: true
