name: Release
on:
  push:
    branches:
      - main
permissions:
   contents: write 
   packages: write 
jobs:
  release:
    if: ${{ github.actor == 'biohackerellie'}}
    runs-on: ubuntu-latest
    permissions:
      contents: write
      id-token: write
      packages: write
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0 
      - uses: actions/setup-go@v5
        with:
          go-version: stable
          cache: true
          check-latest: true
      - uses: ./.github/actions/setup
      - name: Build Typescript
        run: pnpm build

      - name: Create Version
        id: changesets
        uses: changesets/action@v1
        with:
          version: node .github/changeset-version.js
          publish: npx changeset publish
          createGithubReleases: false
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
          NPM_TOKEN: ${{secrets.NPM_TOKEN}}
          NODE_ENV: "production"
      - uses: goreleaser/goreleaser-action@v6 
        if: steps.changesets.outputs.published == 'true'
        with:
          args: release --clean
          version: ${{ env.GITHUB_REF_NAME }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
