name: Release
on:
  push:
    branches:
      - main
permissions:
   contents: write 
   packages: write 
jobs:
  release:
    if: ${{ github.actor == 'biohackerellie'}}
    runs-on: ubuntu-latest
    permissions:
      contents: write
      id-token: write
      packages: write
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0 
      - uses: actions/setup-go@v5
        with:
          go-version: stable
          cache: true
          check-latest: true
      - uses: ./.github/actions/setup
      - name: Build Typescript
        run: pnpm build
      - name: Create Release
        id: changeset
        uses: changesets/action@v1.4.7
        with:
          commit: "chore(release): ?? version packages"
          title: "chore(release): ??  version packages"
          publish: npx changeset publish
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
